name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js 14.x
        uses: actions/setup-node@v4
        with:
          node-version: 14.x
      - name: Install npm 6.14.18
        run: npm install -g npm@6.14.18
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Start the application
        run: npm run dev
      - name: Cypress run
        run: npm run cypress:run