name: E2E test

on: push

jobs:
  linting-on-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Installing dependencies
        run: |
          npm ci

      - name: Linting
        run: |
          npm run build
      - name: Creating workspace
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: ./.next

  cypress-e2e-testing:
    needs: linting-on-build
    runs-on: ubuntu-22.04
    steps:
      - name: Download build output
        uses: actions/download-artifact@v2
        with:
          name: build-output

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
        with:
          start: npm run start
