name: E2E test

on: push

jobs:
  linting-on-build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      
      - name: Installing dependencies
        run: |
          npm ci

      - name: Linting
        run: |
          npm run build
      - name: Creating workspace
        uses: actions/upload-artifact@v3
        with:
          name: .next
          path: ./.next

  cypress-e2e-testing:
    needs: linting-on-build
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        containers: [1, 2, 3, 4]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Download build output
        uses: actions/download-artifact@v3
        with:
          name: .next
          path: .next

      - name: Show repo structure
        run: |
          ls -lad
      
      - name: Install Cypress
        run: npm i cypress@13.6.0

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          SERVICE_ROLE_KEY: ${{ secrets.SERVICE_ROLE_KEY}}

        with:
          start: npm run start
          install: false
          parallel: true
